Repository GO-SOPT-SOPTKATHON-TEAM4/team4-server, pull requests merged in 2023-05, with the labels that each got.

#7 #5 [feat] 게시글 상세조회 api 구현
  src/main/java/com/sopt/sopkathonproduct/controller/PostController.java
  src/main/java/com/sopt/sopkathonproduct/domain/entity/Post.java
  src/main/java/com/sopt/sopkathonproduct/dto/response/PostResponseDto.java
  src/main/java/com/sopt/sopkathonproduct/exception/ErrorStatus.java
  src/main/java/com/sopt/sopkathonproduct/exception/NotFoundException.java
  src/main/java/com/sopt/sopkathonproduct/exception/SoptException.java
  src/main/java/com/sopt/sopkathonproduct/exception/SuccessStatus.java
  src/main/java/com/sopt/sopkathonproduct/repository/PostRepository.java
  src/main/java/com/sopt/sopkathonproduct/service/PostService.java
  src/main/java/com/sopt/sopkathonproduct/service/S3Service.java
Labels: feat, 유난🐻, pull request🔥

#8 #2 [feat] 랭킹 업데이트, 토너먼트 조회 API 구현
  src/main/java/com/sopt/sopkathonproduct/common/domain/BaseEntity.java
  src/main/java/com/sopt/sopkathonproduct/controller/PostController.java
  src/main/java/com/sopt/sopkathonproduct/domain/entity/Post.java
  src/main/java/com/sopt/sopkathonproduct/dto/response/RandomPostResponseDTO.java
  src/main/java/com/sopt/sopkathonproduct/service/PostService.java
  src/main/java/com/sopt/sopkathonproduct/service/RankingService.java
Labels: 유난🐻

#9 #4 [feat] 게시물 랭킹 리스트 조회 api
  src/main/java/com/sopt/sopkathonproduct/controller/PostController.java
  src/main/java/com/sopt/sopkathonproduct/domain/entity/Post.java
  src/main/java/com/sopt/sopkathonproduct/dto/response/PostListResponseDTO.java
  src/main/java/com/sopt/sopkathonproduct/dto/response/PostResponseDTO.java
  src/main/java/com/sopt/sopkathonproduct/dto/response/PostResponseDto.java
  src/main/java/com/sopt/sopkathonproduct/service/PostService.java
Labels: feat, pull request🔥, 영주🐼

#11 #10 [refactor] Builder 수정
  src/main/java/com/sopt/sopkathonproduct/controller/PostController.java
  src/main/java/com/sopt/sopkathonproduct/domain/entity/Post.java
  src/main/java/com/sopt/sopkathonproduct/dto/response/PostListResponseDTO.java
  src/main/java/com/sopt/sopkathonproduct/dto/response/PostResponseDTO.java
  src/main/java/com/sopt/sopkathonproduct/dto/response/RandomPostResponseDTO.java
  src/main/java/com/sopt/sopkathonproduct/repository/PostRepository.java
  src/main/java/com/sopt/sopkathonproduct/service/PostService.java
Labels: 영주🐼, refact
